apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: hello
  name: hello
  namespace: default

spec:

  replicas: 2

  selector:
    matchLabels:
      name: hello
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: qa
        image: gcr.io/abs-crs-sandbox1/log-demo:latest
        imagePullPolicy: Always
        name: log-demo-1
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
      restartPolicy: Always

      terminationGracePeriodSeconds: 30

